name: Automation test trigger based on comment
on: issue_comment

jobs:
  deploy:
    name: Start testing
    runs-on: ubuntu-latest
    steps:
      - name: Notify test start
        id: update
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ toJSON(github.event.comment.id) }}
          body: |
            **Edit:** Started testing at https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID
          reactions: eyes
      - name: Testing started
        id: testing
        run: echo "Hi testing2 ${{ toJSON(github.event.comment.body) }}"
      - name: Update comment
        id: update
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ toJSON(github.event.comment.id) }}
          body: |
            **Edit:** Some additional info
          reactions: '+1'
