name: Automation test trigger based on comment
on: issue_comment

jobs:
  deploy:
    name: Start testing
    runs-on: ubuntu-latest
    if: contains( github.event.comment.body, '@test')
    steps:
      - name: Get Github actor
        id: get_github_actor
        run: echo ::set-env name=ACTOR::$(echo $GITHUB_ACTOR)
      - name: Notify test start
        id: notify_testing
        env:
          GITHUB_ACTOR: ${{env.GITHUB_ACTOR}}
          ACTOR: ${{env.ACTOR}}
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ toJSON(github) }}
          body: |
            **Edit:** Started testing at https://github.com/${{github.repository}}/actions/runs/${{github.run_id}} by ${{ env.ACTOR }} and ${{ env.GITHUB_ACTOR }}
          reactions: eyes
