name: Automation test trigger based on comment
on: issue_comment

jobs:
  deploy:
    name: Start testing
    runs-on: ubuntu-latest
    steps:
      - name: Start Testing
        id: testing
        run: echo "Hi testing2 ${{ toJSON(github.event.comment.body) }}"
      - name: Update comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ github.event.comment.id }}
          body: |
            **Edit:** Some additional info
          reactions: eyes
