name: Automation test trigger based on comment
on: issue_comment

jobs:
  deploy:
    name: Start testing
    runs-on: ubuntu-latest
    if: contains( github.event.comment.body, '@test')
    steps:
      - name: Notify test start
        id: notify_testing
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ toJSON(github.event.comment.id) }}
          body: |
            **Edit:** Started testing at https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
          reactions: eyes
      - uses: actions/checkout@v1
      - name: Prepare repository
        run: echo "Hi ${GITHUB_REF:11}"
      - name: Update comment
        id: update_result
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ toJSON(github.event.comment.id) }}
          body: |
            **Edit:** Some additional info
          reactions: '+1'
