name: Automation test trigger based on comment
on: issue_comment

jobs:
  deploy:
    name: Start testing
    runs-on: ubuntu-latest
    if: contains( github.event.comment.body, '@test')
    steps:
      - name: Notify test start
        run: echo $GITHUB_ACTOR
